### ISSUE TITLE
ChangeIdracUserPasswordREDFISH.py always signals failure... but works

### ISSUE THREAD

**Issue by KeithBierman** [dell/iDRAC-Redfish-Scripting#126]
python3 $DHOME/ChangeIdracUserPasswordREDFISH.py -ip $IDRACIP -uroot -p $IDRACPASS -id 3 -np $NEWPASS

- PASS, status code 200 returned for PATCH command to change iDRAC user password
- WARNING, executing GET request using new password for validating successful change

- FAIL, status code 401 returned for GET command. Detail error results:
{'error': {'code': 'Base.1.0.GeneralError', 'message': 'A general error has occurred. See ExtendedInfo for more information.', '@Message.ExtendedInfo': [{'@odata.type': '#Message.v1_0_0.Message', 'MessageId': 'Base.1.2.AccessDenied', 'Message': 'The authentication credentials included with this request are missing or invalid.', 'MessageArgs': [], 'MessageArgs@odata.count': 0, 'RelatedProperties': [], 'RelatedProperties@odata.count': 0, 'Severity': 'Critical', 'Resolution': 'Attempt to ensure that the URI is correct and that the service has the appropriate credentials.'}]}}

**Comment by KeithBierman** [comment]
By works, I mean that the password for the user.slot is changed as expected.

**Comment by jonas-werner** [comment]
@KeithBierman Just an observation: Could this be because you're executing the script as the same user you're changing the password for? 

Basically, the script is executed as root, then the password is changed and the script is still running using the old password and getting the error when checking the status of the job? 

As a test, if you'd try changing the password for any other user (but still using the root user to execute the job) would you get the same issue?

**Comment by KeithBierman** [comment]
yes. Indeed all of my testing was for changing users not root while being root.

**Comment by texroemer** [comment]
Hi @KeithBierman 

Just tried the script and unable to hit the issue you are seeing. Can you let me know if you are passing in any special characters for the new password? 

I updated the script and added retries for GET using the new password. Issue could be that iDRAC is taking a bit longer for the change to be accepted since you stated the password does get changed.

**Comment by KeithBierman** [comment]
With the change, we still fail but perhaps this is a clearer clue 

DHOME is where the python scripts are, etc. id slot 2 is root and I'm not changing root (indeed, in our flow (CryptoErase, IDRAC, ImportSystemConfig, everything is reset except the MAAS user (for some reason it's mangled, but the MAAS user is "special" in that it has no role, but is an IPMI administrator) so we change it with a an extra call ... )

python3 $DHOME/ChangeIdracUserPasswordREDFISH.py -ip $IDRACIP -uroot -p $IDRACPASS -id 4 -np $MAASPASS

- PASS, status code 200 returned for PATCH command to change iDRAC user password
- WARNING, executing GET request using new password for validating successful change
...
max of 10 reached
..

**Comment by KeithBierman** [comment]
as for "special characters" no, it's just a-z (being a test, rather than Production, I wasn't trying for anything fancy. Mork for example is one of the test cases

**Comment by texroemer** [comment]
Script bug which i fixed, new version uploaded. GET request wasn't handling the correct user account ID being changed and also wasn't checking if user privilege is set to None. When set to None, GET requests will not work.

Examples of executing new script.

This example changes password for iDRAC user ID 4 using iDRAC user ID 4 username / password.
 
C:\Python38-32>ChangeIdracUserPasswordREDFISH.py -ip 192.168.0.120 -u User4 -p Test1234! -id 4 -np Test1234#

- PASS, status code 200 returned for PATCH command to change iDRAC user password for user ID 4
- WARNING, executing GET request to validate using new password for iDRAC user ID 4
- PASS, status code 200 returned for GET command, iDRAC user password change successful for account ID 4

This example changes password for iDRAC user ID 4 with read only privileges using iDRAC user ID 2 username / password.

C:\Python38-32>ChangeIdracUserPasswordREDFISH.py -ip 192.168.0.120 -u root -p calvin -id 4 -np Test1234!

- PASS, status code 200 returned for PATCH command to change iDRAC user password for user ID 4
- WARNING, executing GET request to validate using new password for iDRAC user ID 4
- PASS, status code 200 returned for GET command, iDRAC user password change successful for account ID 4

This example changes password for iDRAC user ID 4 with None privileges using iDRAC user ID 2 username / password. 

C:\Python38-32>ChangeIdracUserPasswordREDFISH.py -ip 100.65.84.79 -u root -p calvin -id 4 -np Test1234#

- PASS, status code 200 returned for PATCH command to change iDRAC user password for user ID 4
- WARNING, executing GET request to validate using new password for iDRAC user ID 4
- WARNING, iDRAC user "User4" privileges set to None, password is changed but unable to execute GET request due to incorrect privilege level

**Comment by KeithBierman** [comment]
Perfect!

Kudos for these scripts. Nits aside, we are finding them very helpful and the diagnostics demonstrably better than mature racadm and the GUI tools.
