### ISSUE TITLE
Prevent Auto-reboot when using SimpleUpdate TransferProtocol based firmware update

### ISSUE THREAD

**Issue by capriguy84** [dell/iDRAC-Redfish-Scripting#136]
Hi - 

Is there a way to prevent the Automatic reboot job from being created on idrac 4.00 and above when SimpleUpdate Transfer Protocol=HTTP is used? I love the idea of not having to upload the image and just pass the uri payload  for the drac. I understand the same may not work for idrac, diagnotics and driver pack dups.

FWIW, I staged a BIOS update dup and the server immediately rebooted. The api docs do not mention this.
[RF API documentation at dell.com](https://www.dell.com/support/manuals/us/en/04/idrac9-lifecycle-controller-v4.x-series/idrac9_4.00.00.00_redfishapiguide_pub/updating-firmware-using-simpleupdate?guid=guid-97450585-1a7c-48a4-b7e5-8385585e2d8b&lang=en-us)

Thanks

**Comment by texroemer** [comment]
Hi @capriguy84 

This is a known bug in 4.00, 4.10 iDRAC versions and has been resolved in 4.22 iDRAC. See examples below where using 4.22 iDRAC, i don't reboot now and reboot now.


```
C:\Python38-32>racadm -r 192.168.0.120 -u root -p calvin --nocertwarn getversion -f idrac
 iDRAC Version                    = 4.22.00.00

C:\Python38-32>DeviceFirmwareSimpleUpdateTransferProtocolREDFISH.py -ip 192.168.0.120-u root -p calvin --uri http://192.168.0.130/http_share/BIOS_HC85T_WN64_2.8.2_02.EXE -t HTTP **-r n**

- PASS, JID_002143421288 firmware update job ID successfully created for update image "BIOS_HC85T_WN64_2.8.2_02.EXE"
- INFO: New, current job execution time: 0:00:01
- INFO: New, current job execution time: 0:00:05
- INFO: Downloading the BIOS_HC85T_WN64_2.8.2_02.EXE update package., current job execution time: 0:00:08
- INFO: Downloading the BIOS_HC85T_WN64_2.8.2_02.EXE update package., current job execution time: 0:00:12
- INFO: Package successfully downloaded., current job execution time: 0:00:15
- INFO: Package successfully downloaded., current job execution time: 0:00:19
- INFO: Package successfully downloaded., current job execution time: 0:00:22
- PASS, job ID marked as scheduled

- WARNING, user selected to not reboot the server to apply the update. Update job is still scheduled and will be applied on next server reboot

 C:\Python38-32>DeviceFirmwareSimpleUpdateTransferProtocolREDFISH.py -ip 192.168.0.120 -u root -p calvin --uri http://192.168.0.130/updates_http/BIOS_HC85T_WN64_2.8.2_02.EXE -t HTTP **-r y**

- PASS, JID_002152553029 firmware update job ID successfully created for update image "BIOS_HC85T_WN64_2.8.2_02.EXE"
- INFO: New, current job execution time: 0:00:01
- INFO: New, current job execution time: 0:00:05
- INFO: Downloading the BIOS_HC85T_WN64_2.8.2_02.EXE update package., current job execution time: 0:00:08
- INFO: Downloading the BIOS_HC85T_WN64_2.8.2_02.EXE update package., current job execution time: 0:00:12
- INFO: Package successfully downloaded., current job execution time: 0:00:15
- INFO: Package successfully downloaded., current job execution time: 0:00:19
- INFO: Package successfully downloaded., current job execution time: 0:00:22
- PASS, job ID marked as scheduled

- INFO, rebooting server to execute update job, current server power state is: On
- PASS, Command passed to gracefully power OFF server, code return is 204
- PASS, GET command passed to verify server is in OFF state
- PASS, Command passed to power ON server, code return is 204
- INFO, job status not completed, current status: "Task successfully scheduled.", execution time: "0:00:53"
- INFO, job status not completed, current status: "Task successfully scheduled.", execution time: "0:01:07"
- INFO, job status not completed, current status: "Task successfully scheduled.", execution time: "0:01:21"
- INFO, job status not completed, current status: "Task successfully scheduled.", execution time: "0:01:35"
- INFO, job status not completed, current status: "The specified job is in progress.", execution time: "0:01:53"
- INFO, job status not completed, current status: "The specified job is in progress.", execution time: "0:02:07"
- INFO, job status not completed, current status: "The specified job is in progress.", execution time: "0:02:21"
- INFO, job status not completed, current status: "The specified job is in progress.", execution time: "0:02:35"
- INFO, job status not completed, current status: "The specified job is in progress.", execution time: "0:02:50"
- INFO, job status not completed, current status: "The specified job is in progress.", execution time: "0:03:04"
- INFO, job status not completed, current status: "The specified job is in progress.", execution time: "0:03:18"
- INFO, job status not completed, current status: "The specified job is in progress.", execution time: "0:03:33"
- INFO, job status not completed, current status: "The specified job is in progress.", execution time: "0:03:47"
- INFO, job status not completed, current status: "The specified job is in progress.", execution time: "0:04:01"
- INFO, job status not completed, current status: "The specified job is in progress.", execution time: "0:04:15"
- INFO, job status not completed, current status: "The specified job is in progress.", execution time: "0:04:29"

- PASS, job ID JID_002152553029 successfully marked completed

- Final detailed job results -

@odata.type: #DellJob.v1_0_2.DellJob
CompletionTime: 2020-09-15T19:18:49
Description: Job Instance
EndTime: TIME_NA
Id: JID_002152553029
JobState: Completed
JobType: FirmwareUpdate
Message: The specified job has completed successfully.
MessageArgs: []
MessageId: PR19
Name: Firmware Update: BIOS
PercentComplete: 100
StartTime: TIME_NOW
TargetSettingsURI: None

- JOB ID JID_002152553029 completed in 0:04:44
```

**Comment by capriguy84** [comment]
This particular bug is still not patched for R620 model running latest idrac v 2.65.65.65. Any idea if that will be patched in upcoming releases? Is Dell aware of this issue?

**Comment by texroemer** [comment]
Hi @capriguy84 

This issue has been resolved in iDRAC 7/8 2.75 version which is the latest posted on Dell support site. 

See example below using iDRAC 2.75, no reboot job ID is getting created in the job queue.


```
C:\Python38-32>DeleteJobIdREDFISH.py -ip 192.168.0.120 -u root -p calvin -q y

- WARNING, job queue empty, no current job IDs detected for iDRAC 192.168.0.120

C:\Python38-32>DeviceFirmwareSimpleUpdateTransferProtocolREDFISH.py -ip 192.168.0.120 -u root -p calvin -g y

- INFO, current devices detected with firmware version and updateable status -

Device Name: Power Supply.Slot.1, Firmware Version: 00.10.37, Updatable: True
Device Name: BP13G+ 0:1, Firmware Version: 2.25, Updatable: True
Device Name: PERC H730 Mini, Firmware Version: 25.5.5.0005, Updatable: True
Device Name: OS COLLECTOR 1.1, OSC_1.1, A00, Firmware Version: OSC_1.1, Updatable: True
Device Name: Disk 0 in Backplane 1 of Integrated RAID Controller 1, Firmware Version: VT31, Updatable: True
Device Name: BIOS, Firmware Version: 2.7.1, Updatable: True
Device Name: Dell OS Driver Pack, 18.11.00, A00, Firmware Version: 18.11.00, Updatable: True
**Device Name: Integrated Dell Remote Access Controller, Firmware Version: 2.75.75.75, Updatable: True**
Device Name: Dell 64 Bit uEFI Diagnostics, version 4239A37, 4239.45, Firmware Version: 4239A37, Updatable: True
Device Name: QLogic 577xx/578xx 10 Gb Ethernet BCM57810 - 00:0A:F7:5D:7A:70, Firmware Version: 14.04.18, Updatable: True
Device Name: Broadcom Gigabit Ethernet BCM5720 - 44:A8:42:46:9C:2C, Firmware Version: 7.10.64, Updatable: True
Device Name: System CPLD, Firmware Version: 1.0.1, Updatable: True
Device Name: Lifecycle Controller, Firmware Version: 2.75.75.75, Updatable: False

C:\Python38-32>DeviceFirmwareSimpleUpdateTransferProtocolREDFISH.py -ip 192.168.0.120 -u root -p calvin -t HTTP --uri http://192.168.0.130/updates_http/BIOS_7YNRC_WN64_2.11.0_latest.EXE -r n

- PASS, JID_091701023802 firmware update job ID successfully created for update image "BIOS_7YNRC_WN64_2.11.0_latest.EXE"
- INFO: New job., current job execution time: 0:00:02
- INFO: Downloading the BIOS_7YNRC_WN64_2.11.0_latest.EXE update package., current job execution time: 0:00:08
- INFO: Downloading the BIOS_7YNRC_WN64_2.11.0_latest.EXE update package., current job execution time: 0:00:14
- INFO: Downloading the BIOS_7YNRC_WN64_2.11.0_latest.EXE update package., current job execution time: 0:00:19
- INFO: Downloading the BIOS_7YNRC_WN64_2.11.0_latest.EXE update package., current job execution time: 0:00:24
- INFO: Downloading the BIOS_7YNRC_WN64_2.11.0_latest.EXE update package., current job execution time: 0:00:30
- INFO: Downloading the BIOS_7YNRC_WN64_2.11.0_latest.EXE update package., current job execution time: 0:00:35
- INFO: Downloading the BIOS_7YNRC_WN64_2.11.0_latest.EXE update package., current job execution time: 0:00:40
- INFO: Package successfully downloaded., current job execution time: 0:00:44
- INFO: Package successfully downloaded., current job execution time: 0:00:48
- PASS, job ID marked as scheduled

- WARNING, user selected to not reboot the server to apply the update. Update job is still scheduled and will be applied on next server reboot

C:\Python38-32>DeleteJobIdREDFISH.py -ip 192.168.0.120 -u root -p calvin -q y

- Current job IDs in the job queue for iDRAC 192.168.0.120:

--------------------------------------------------------------------------------
Job ID: JID_091701023802
Job Type: Firmware Update: BIOS
Job Message: Task successfully scheduled.
```

**Comment by capriguy84** [comment]
The latest idrac firmware for R620 which is 12G server still shows as 2.65.65.65

[Link1](https://www.dell.com/support/home/en-us/product-support/product/poweredge-r620/drivers)
[Link2](http://poweredgec.dell.com/latest_poweredge-12g.html#R620%20iDRAC%20with%20Lifecycle%20controller)

The 2.75.75.75 is idrac 8 that doesn't have this problem.

**Comment by texroemer** [comment]
Hi @capriguy84 

Sorry about that, missed you referenced 12G server, not 13G server which currently this issue does exist in latest iDRAC posted on Dell support site for 12G. 

I just escalated this issue, will keep you posted on any details i hear. 

Thanks

**Comment by texroemer** [comment]
Hi @capriguy84 

Can you go ahead and escalate this issue to Dell Tech Support? This issue would need to go through the correct channels at Dell to get escalated for a new iDRAC firmware posted with the fix.

Thanks
